### PR TITLE
Homework21

### PR DESCRIPTION
**Pull request by Juhkri**
Not working. The CSS element prob isn't correct but I tried 3 times with different names.

### CODE REVIEW

**Comment by khanhtestpro** [comment]
//Comment from HW team
Hi,
I have reviewed homework 21 you submitted. Homework 21 purpose of Web Elements + Action Class, but in your branch i don't see any test implementing it, i only see the test part of homework 20 about wait. 
Maybe you submitted wrong, please recheck and submit correct assignment homework21

**Comment by khanhtestpro** [comment]
Beside, about issue `Not working. The CSS element prob isn't correct but I tried 3 times with different names.`. I try run your homework 20, and it failed at step with error `org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.cssSelector: [data-testid='playlist-context-menu-create-simple'] (tried for 4 second(s) with 500 milliseconds interval)`

image

because when successfully logged into the web, it is necessary to wait for a hardcoded time for the element to load as image example below
image

Locator Create a new playlist a  = [data-testid="sidebar-create-playlist-btn"] although already visible in DOM and clickable but when not load done, click on it can't display locator New Playlist = [data-testid='playlist-context-menu-create-simple'], so it timeout to find element and failed 

If all wait condition fails, you might consider using Thread.sleep() as a temporary workaround
example:

image

image

**Comment by Juhkri** [comment]
https://prnt.sc/ixJ-tBWWT1Ai

Thread sleep is there already. It is under the createPlaylist method. I put it there because there's a likelihood that it would always need to be done for that method specifically.

**Comment by Juhkri** [comment]
I think it was submitted wrong if you're seeing that. I'll try submitting again.

**Pull request closed without merging**
